baseURL = "http://example.org/"
theme = "LoveIt"
title = "Malware And Reversing Engine"
languageCode = "zh-cn"
hasCJKLanguage = true
languageName = "简体中文"
enableRobotsTXT = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[params]
  # 网站默认主题样式 ["auto", "light", "dark"]
  defaultTheme = "dark"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  # LoveIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt 新增 | 0.2.0 日期格式
  dateFormat = "2006-01-02"
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "Malware And Reversing"
  # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "Welcome to Malware And Reversing"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]

  # 作者配置
  [params.author]
    name = "B0ltec"
    email = ""
    link = ""

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = "Malware And Reversing"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = true

  # 页面底部信息配置
  [params.footer]
    enable = true
    # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
    custom = ''
    # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = true
    # LoveIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # LoveIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2025 
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

   # 主页配置
  [params.home]
    # LoveIt 新增 | 0.2.0 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = ""
      # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "malware and reversing"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
      disclaimer = "免责声明：本博客文章仅用于教育和研究目的。由于传播或利用此文所提供的信息、技术或方法而造成的任何直接或间接的后果及损失，均由使用者本人负责， 文章作者不为此承担任何责任。"

    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      # LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

  #文章全局配置
  [params.page]
    # LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # LoveIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # LoveIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true

  #代码配置
  [params.page.code]
    # 是否显示代码块的复制按钮
    copy = true
    # 默认展开显示的代码行数
    maxShownLines = 50

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = "<i class=\"fa-solid fa-square-pen\"></i>"
    post = ""
    name = "Blog"
    url = "/posts/"
    title = "Blog"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = "<i class=\"fa-solid fa-tag\"></i>"
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "Tags"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = "<i class=\"fa-solid fa-folder\"></i>"
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Categories"

[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  # LoveIt 更改 | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
